sudo npm install -g gulp
sudo npm install -g gulp-sass
sudo npm install -g gulp-concat
sudo npm install -g gulp-util
sudo npm install -g gulp-minify-css
sudo npm install -g gulp-rename
sudo npm install -g shelljs
sudo npm install -g karma
sudo npm install -g jasmine
sudo npm install -g jasmine-core
sudo npm install -g karma-jasmine
sudo npm install -g phantomjs
sudo npm install -g karma-phantomjs-launcher
